language: node_js

cache:
  directories:
    - "$HOME/.npm"

node_js:
  - 'node'

install:
  - npm ci && cd test/webpack3 && npm ci && cd ../webpack4 && npm ci && cd ../webpack4-htmlplugin4 && npm ci && cd ../..
